language:
  php

php:
  - 7.0

env:
  global:
    - KEY_SERVER="hkp://keyserver.ubuntu.com:80"
    - MONGO_REPO_URI="http://repo.mongodb.com/apt/ubuntu"
    - MONGO_REPO_TYPE="precise/mongodb-enterprise/"
    - SOURCES_LOC="/etc/apt/sources.list.d/mongodb.list"
  matrix:
    - DRIVER_VERSION=1.1.2 SERVER_VERSION=2.6
    - DRIVER_VERSION=1.1.2 SERVER_VERSION=3.0
    - DRIVER_VERSION=1.1.2 SERVER_VERSION=3.2

before_install:
  - sudo apt-key adv --keyserver ${KEY_SERVER} --recv 7F0CEB10
  - sudo apt-key adv --keyserver ${KEY_SERVER} --recv EA312927
  - echo "deb ${MONGO_REPO_URI} ${MONGO_REPO_TYPE}${SERVER_VERSION} multiverse" | sudo tee ${SOURCES_LOC}
  - sudo apt-get update -qq

install:
  - sudo apt-get install mongodb-enterprise
  - sudo apt-get -y install gdb

before_script:
  - phpenv config-rm xdebug.ini
  - if ! nc -z localhost 27017; then sudo service mongod start; fi
  - mongod --version
  - pecl install -f mongodb-${DRIVER_VERSION}
  - if [ "$(php -v | grep 'PHP 5.4')" ]; then echo 'extension = mongodb.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - php --ri mongodb
  - composer install --dev --no-interaction --prefer-source
  - ulimit -c
  - ulimit -c unlimited -S

# set up composer
#before_script:
#  - curl -s https://getcomposer.org/installer | php
#  - php ./composer.phar --no-progress --dev install

# run the phpunit tests
script:
  - php ./vendor/bin/phpunit --coverage-text